

function saveGame() {
  console.log("Saving game");
  const gameSave = {
    game: game,

    flyweightFighters: flyweightFighters,
    bantamweightFighters: bantamweightFighters,
    featherweightFighters: featherweightFighters,
    lightweightFighters: lightweightFighters,
    welterweightFighters: welterweightFighters,

    flyweightpUgrades: flyweightUpgrades
  };
  game.lastPlayed = Date.now();
  localStorage.setItem("gameSave", JSON.stringify(gameSave));
}

function loadGame() {
  let now = Date.now();
  let offlineTime = now -= game.lastPlayed;
    
  const gameSave = localStorage.getItem("gameSave");
  if (gameSave === null) {
    console.error("No game save found");
    return;
  }
  const parsedGameSave = JSON.parse(gameSave);

  game = parsedGameSave.game;

  flyweightFighters = parsedGameSave.flyweightFighters;
  bantamweightFighters = parsedGameSave.bantamweightFighters;
  featherweightFighters = parsedGameSave.featherweightFighters;
  lightweightFighters = parsedGameSave.lightweightFighters;
  welterweightFighters = parsedGameSave.welterweightFighters;

  flyweightUpgrades = parsedGameSave.flyweightUpgrades;

  if (game.flyweightActive && game.activeTrainers <= game.maxTrainers) {
    clearInterval(game.intervalId);
    clearInterval(flyweightFighters.intervalIndex as unknown as number);
    if (offlineTime >= 1_000) {
      flyweightInterval(flyweightFighters.intervalIndex as unknown as number);
      offlineGains(flyweightFighters.intervalIndex as unknown as number);
    }
  }
  if (game.bantamweightActive && game.activeTrainers <= game.maxTrainers) {
    clearInterval(game.intervalId);
    clearInterval(bantamweightFighters.intervalIndex as unknown as number);
    if (offlineTime >= 1_000) {
      bantamweightInterval(bantamweightFighters.intervalIndex as unknown as number);
      offlineGains(bantamweightFighters.intervalIndex as unknown as number);
    }
  }
  if (game.featherweightActive && game.activeTrainers <= game.maxTrainers) {
    clearInterval(game.intervalId);
    clearInterval(featherweightFighters.intervalIndex as unknown as number);
    if (offlineTime >= 1_000) {
      featherweightInterval(featherweightFighters.intervalIndex as unknown as number);
      offlineGains(featherweightFighters.intervalIndex as unknown as number);
    }
  }
  if (game.lightweightActive && game.activeTrainers <= game.maxTrainers) {
    clearInterval(game.intervalId);
    clearInterval(lightweightFighters.intervalIndex as unknown as number);
    if (offlineTime >= 1_000) {
      lightweightInterval(lightweightFighters.intervalIndex as unknown as number);
      offlineGains(lightweightFighters.intervalIndex as unknown as number);
    }
  }
  if (game.welterweightActive && game.activeTrainers <= game.maxTrainers) {
    clearInterval(game.intervalId);
    clearInterval(welterweightFighters.intervalIndex as unknown as number);
    if (offlineTime >= 1_000) {
      welterweightInterval(welterweightFighters.intervalIndex as unknown as number);
      offlineGains(welterweightFighters.intervalIndex as unknown as number);
    }
  }
updateUi();
console.log("Game loaded");
}

function resetGame() {
  localStorage.removeItem("gameSave");
  game = {
    version: "0.2.28",
    hampaita: 1.000,
    hampaitaPerSekunti: 0.0,
    totalPower: 0,
    verta: 0,
    activeTrainers: 0,
    maxTrainers: 1,
    freeTrainers: 0,
    rebirths: 0,
    veriKerroin: 0.00_000_1,
    avaaSatunnainenHinta: 1,
    avaaValitsemaHinta: 100,
    rebirthFor: 0,
    shopOpen: false,
    lastPlayed: 0,
    activeFighter: "",
    activeWeightclass: "",
    app: document.getElementById("app"),
    intervalId: -1,
    now: Date.now(),

    globalSpeedMulti: 1,
    globalPowerMulti: 1,
    globalXpThreshMulti: 1.4,
    
    flyweightThreshMultiMulti: 0.99,
    bantamweightThreshMultiMulti: 0.99,
    featherweightThreshMultiMulti: 0.99,
    lightweightThreshMultiMulti: 0.99,
    welterweightThreshMultiMulti: 0.99,
    flyweightSpeedMulti: 1,
    bantamweightSpeedMulti: 1,
    featherweightSpeedMulti: 1,
    lightweightSpeedMulti: 1,
    welterweightSpeedMulti: 1,

    flyweightXp: 0,
    flyweightXpThresh: 10,
    flyweightLevel: 0,
    flyweightStep: 0.01,
    flyweightCount: 0,
    flyweightActive: false,

    bantamweightXp: 0,
    bantamweightXpThresh: 10,
    bantamweightLevel: 0,
    bantamweightStep: 0.01,
    bantamweightCount: 0,
    bantamweightActive: false,

    featherweightXp: 1,
    featherweightXpThresh: 10,
    featherweightLevel: 0,
    featherweightStep: 0.01,
    featherweightCount: 0,
    featherweightActive: false,

    lightweightXp: 0,
    lightweightXpThresh: 10,
    lightweightLevel: 0,
    lightweightStep: 0.01,
    lightweightCount: 0,
    lightweightActive: false,

    welterweightXp: 0,
    welterweightXpThresh: 10,
    welterweightLevel: 0,
    welterweightStep: 0.01,
    welterweightCount: 0,
    welterweightActive: false,

    totalCount: 0,
    jenkkiCount: 0,
    brassiCount: 0,
    strikerCount: 0,
    grapplerCount: 0,
    alle30Count: 0,
    ladyWaistCount: 0,
    pelleCount: 0,
    niceGuyCount: 0,
    stanCount: 0,
    afrikanMafiaCount: 0,
    lookingAssCount: 0,
    chadCount: 0,
    championCount: 0,
    lasiLeukaCount: 0,
    legHuggerCount: 0,
    unrankedCount: 0,
    chickenCount: 0,
    hasBeenCount: 0,
  };
  flyweightFighters = {
    nimi: [
      "Cody Durden",
      "Asu Almabayev",
      "Bruno Silva",
      "Tagir Ulanbekov",
      "Matt Schnell",
    ],
    power: [1.0, 1.1, 1.21, 1.331, 1.464],
    speed: [1, 0.9, 0.81, 0.729, 0.656],
    level: [0, 0, 0, 0, 0],
    hinta: [10, 100, 1_000, 10_000, 100_000],
    numero: [0, 1, 2, 3, 4],
    progress: [0, 0, 0, 0, 0],
    step: [1, 0.9, 0.81, 0.729, 0.656],
    visibleReq: [0, 15, 30, 45, 60],
    unlockReq: [0, 5, 10, 15, 20],
    totalPower: [0.0, 0.0, 0.0, 0.0, 0.0],
    isVisible: [true, false, false, false, false],
    isUnlocked: [true, false, false, false, false],
    isActive: [false, false, false, false, false],
    xp: [0, 0, 0, 0, 0],
    xpThresh: [5, 5, 5, 5, 5],
    img: [
      "./assets/codyDurden.png",
      "./assets/asuAlmabayev.png",
      "./assets/brunoSilva.png",
      "./assets/tagirUlanbekov.png",
      "./assets/mattSchnell.png",
    ],
    id: [
      "codyDurden",
      "asuAlmabayev",
      "brunoSilva",
      "tagirUlanbekov",
      "mattSchnell",
    ],
    interval: [null, null, null, null, null],
    intervalIndex: null,
    divEl: [
      document.getElementById("codyDurdenContainer") as HTMLDivElement,
      document.getElementById("asuAlmabayevContainer") as HTMLDivElement,
      document.getElementById("brunoSilvaContainer") as HTMLDivElement,
      document.getElementById("tagirUlanbekovContainer") as HTMLDivElement,
      document.getElementById("mattSchnellContainer") as HTMLDivElement,
    ],
    mastery10Unlcked: [false, false, false, false, false],
    mastery20Unlcked: [false, false, false, false, false],
    mastery30Unlcked: [false, false, false, false, false],
    mastery40Unlcked: [false, false, false, false, false],
    mastery50Unlcked: [false, false, false, false, false],
    mastery60Unlcked: [false, false, false, false, false],
    mastery70Unlcked: [false, false, false, false, false],
    mastery80Unlcked: [false, false, false, false, false],
    mastery90Unlcked: [false, false, false, false, false],
    mastery100Unlcked: [false, false, false, false, false],
    mastery10Done: 0,
    mastery20Done: 0,
    mastery30Done: 0,
    mastery40Done: 0,
    mastery50Done: 0,
    mastery60Done: 0,
    mastery70Done: 0,
    mastery80Done: 0,
    mastery90Done: 0,
    mastery100Done: 0,
    mastery10UnlockedFor5: false,
    mastery20UnlockedFor5: false,
    mastery30UnlockedFor5: false,
    mastery40UnlockedFor5: false,
    mastery50UnlockedFor5: false,
    mastery60UnlockedFor5: false,
    mastery70UnlockedFor5: false,
    mastery80UnlockedFor5: false,
    mastery90UnlockedFor5: false,
    mastery100UnlockedFor5: false,
    tags: {
      jenkki: [true, false, false, false, true],
      brassi: [false, false, true, false, false],
      striker: [true, false, false, false, false],
      grappler: [false, false, true, true, false],
      boxing: [false, false, false, false, true],
      alle30: [false, false, false, false, false],
      ladyWaist: [true, false, false, false, false],
      pelle: [false, false, false, false, false],
      niceGuy: [false, false, false, false, false],
      stan: [false, true, false, true, false],
      afrikanMafia: [false, false, false, false, false],
      lookingAss: [false, false, false, true, false],
      chad: [false, false, false, false, false],
      champion: [false, false, false, false, false],
      lasiLeuka: [false, false, false, false, false],
      legHugger: [false, false, false, false, false],
      unranked: [false, false, false, false, false],
      chicken: [false, false, false, false, false],
      hasBeen: [false, false, true, false, false],
    },
  };
  bantamweightFighters = {
    nimi: [
      "Montel Jackson",
      "Dominick Cruz",
      "Jonathan Martinez",
      "Kyler Phillips",
      "Mario Bautista",
    ],
    power: [1.0, 1.1, 1.21, 1.331, 1.464],
    speed: [1, 0.9, 0.81, 0.729, 0.656],
    level: [0, 0, 0, 0, 0],
    hinta: [10, 100, 1_000, 10_000, 100_000],
    numero: [0, 1, 2, 3, 4],
    progress: [0, 0, 0, 0, 0],
    step: [1, 0.9, 0.81, 0.729, 0.656],
    visibleReq: [0, 15, 30, 45, 60],
    unlockReq: [0, 5, 10, 15, 20],
    totalPower: [0.0, 0.0, 0.0, 0.0, 0.0],
    isVisible: [true, false, false, false, false],
    isUnlocked: [true, false, false, false, false],
    isActive: [false, false, false, false, false],
    xp: [0, 0, 0, 0, 0],
    xpThresh: [5, 5, 5, 5, 5],
    img: [
      "./assets/montelJackson.png",
      "./assets/dominickCruz.png",
      "./assets/jonathanMartinez.png",
      "./assets/kylerPhillips.png",
      "./assets/marioBautista.png",
    ],
    id: [
      "montelJackson",
      "dominickCruz",
      "jonathanMartinez",
      "kylerPhillips",
      "marioBautista",
    ],
    interval: [null, null, null, null, null],
    intervalIndex: null,
    divEl: [
      document.getElementById("montelJacksonContainer") as HTMLDivElement,
      document.getElementById("dominickCruzContainer") as HTMLDivElement,
      document.getElementById("jonathanMartinezContainer") as HTMLDivElement,
      document.getElementById("kylerPhillipsContainer") as HTMLDivElement,
      document.getElementById("marioBautistaContainer") as HTMLDivElement,
    ],
    mastery10Unlcked: [false, false, false, false, false],
    mastery20Unlcked: [false, false, false, false, false],
    mastery30Unlcked: [false, false, false, false, false],
    mastery40Unlcked: [false, false, false, false, false],
    mastery50Unlcked: [false, false, false, false, false],
    mastery60Unlcked: [false, false, false, false, false],
    mastery70Unlcked: [false, false, false, false, false],
    mastery80Unlcked: [false, false, false, false, false],
    mastery90Unlcked: [false, false, false, false, false],
    mastery100Unlcked: [false, false, false, false, false],
    mastery10Done: 0,
    mastery20Done: 0,
    mastery30Done: 0,
    mastery40Done: 0,
    mastery50Done: 0,
    mastery60Done: 0,
    mastery70Done: 0,
    mastery80Done: 0,
    mastery90Done: 0,
    mastery100Done: 0,
    mastery10UnlockedFor5: false,
    mastery20UnlockedFor5: false,
    mastery30UnlockedFor5: false,
    mastery40UnlockedFor5: false,
    mastery50UnlockedFor5: false,
    mastery60UnlockedFor5: false,
    mastery70UnlockedFor5: false,
    mastery80UnlockedFor5: false,
    mastery90UnlockedFor5: false,
    mastery100UnlockedFor5: false,
    tags: {
      jenkki: [true, false, false, false, true],
      brassi: [false, false, true, false, false],
      striker: [true, false, false, false, false],
      grappler: [false, false, true, true, false],
      boxing: [false, false, false, false, true],
      alle30: [false, false, false, false, false],
      ladyWaist: [true, false, false, false, false],
      pelle: [false, false, false, false, false],
      niceGuy: [false, false, false, false, false],
      stan: [false, true, false, true, false],
      afrikanMafia: [false, false, false, false, false],
      lookingAss: [false, false, false, true, false],
      chad: [false, false, false, false, false],
      champion: [false, false, false, false, false],
      lasiLeuka: [false, false, false, false, false],
      legHugger: [false, false, false, false, false],
      unranked: [false, false, false, false, false],
      chicken: [false, false, false, false, false],
      hasBeen: [false, false, true, false, false],
    },
  };
  featherweightFighters = {
    nimi: [
      "Edson Barboza",
      "Dan Ige",
      "Bryce Michell",
      "Diego Lopez",
      "Lerone Murphy",
    ],
    power: [1.0, 1.1, 1.21, 1.331, 1.464],
    speed: [1, 0.9, 0.81, 0.729, 0.656],
    level: [0, 0, 0, 0, 0],
    hinta: [10, 100, 1_000, 10_000, 100_000],
    numero: [0, 1, 2, 3, 4],
    progress: [0, 0, 0, 0, 0],
    step: [1, 0.9, 0.81, 0.729, 0.656],
    visibleReq: [0, 15, 30, 45, 60],
    unlockReq: [0, 5, 10, 15, 20],
    totalPower: [0.0, 0.0, 0.0, 0.0, 0.0],
    isVisible: [true, false, false, false, false],
    isUnlocked: [true, false, false, false, false],
    isActive: [false, false, false, false, false],
    xp: [0, 0, 0, 0, 0],
    xpThresh: [5, 5, 5, 5, 5],
    img: [
      "./assets/edsonBarboza.png",
      "./assets/danIge.png",
      "./assets/bryceMichell.png",
      "./assets/diegoLopez.png",
      "./assets/leroneMurphy.png",
    ],
    id: [
      "edsonBarboza",
      "danIge",
      "bryceMichell",
      "diegoLopez",
      "leroneMurphy",
    ],
    interval: [null, null, null, null, null],
    intervalIndex: null,
    divEl: [
      document.getElementById("edsonBarbozaContainer") as HTMLDivElement,
      document.getElementById("danIgeContainer") as HTMLDivElement,
      document.getElementById("bryceMichellContainer") as HTMLDivElement,
      document.getElementById("diegoLopezContainer") as HTMLDivElement,
      document.getElementById("leroneMurphyContainer") as HTMLDivElement,
    ],
    mastery10Unlcked: [false, false, false, false, false],
    mastery20Unlcked: [false, false, false, false, false],
    mastery30Unlcked: [false, false, false, false, false],
    mastery40Unlcked: [false, false, false, false, false],
    mastery50Unlcked: [false, false, false, false, false],
    mastery60Unlcked: [false, false, false, false, false],
    mastery70Unlcked: [false, false, false, false, false],
    mastery80Unlcked: [false, false, false, false, false],
    mastery90Unlcked: [false, false, false, false, false],
    mastery100Unlcked: [false, false, false, false, false],
    mastery10Done: 0,
    mastery20Done: 0,
    mastery30Done: 0,
    mastery40Done: 0,
    mastery50Done: 0,
    mastery60Done: 0,
    mastery70Done: 0,
    mastery80Done: 0,
    mastery90Done: 0,
    mastery100Done: 0,
    mastery10UnlockedFor5: false,
    mastery20UnlockedFor5: false,
    mastery30UnlockedFor5: false,
    mastery40UnlockedFor5: false,
    mastery50UnlockedFor5: false,
    mastery60UnlockedFor5: false,
    mastery70UnlockedFor5: false,
    mastery80UnlockedFor5: false,
    mastery90UnlockedFor5: false,
    mastery100UnlockedFor5: false,
    tags: {
      jenkki: [true, false, false, false, true],
      brassi: [false, false, true, false, false],
      striker: [true, false, false, false, false],
      grappler: [false, false, true, true, false],
      boxing: [false, false, false, false, true],
      alle30: [false, false, false, false, false],
      ladyWaist: [true, false, false, false, false],
      pelle: [false, false, false, false, false],
      niceGuy: [false, false, false, false, false],
      stan: [false, true, false, true, false],
      afrikanMafia: [false, false, false, false, false],
      lookingAss: [false, false, false, true, false],
      chad: [false, false, false, false, false],
      champion: [false, false, false, false, false],
      lasiLeuka: [false, false, false, false, false],
      legHugger: [false, false, false, false, false],
      unranked: [false, false, false, false, false],
      chicken: [false, false, false, false, false],
      hasBeen: [false, false, true, false, false],
    },
  };
  lightweightFighters = {
    nimi: [
      "Paddy Pimblett",
      "Jalin Turner",
      "Rafael Dos Anjos",
      "Benoit Saint Denis",
      "Renato Moicano",
    ],
    power: [1.0, 1.1, 1.21, 1.331, 1.464],
    speed: [1, 0.9, 0.81, 0.729, 0.656],
    level: [0, 0, 0, 0, 0],
    hinta: [10, 100, 1_000, 10_000, 100_000],
    numero: [0, 1, 2, 3, 4],
    progress: [0, 0, 0, 0, 0],
    step: [1, 0.9, 0.81, 0.729, 0.656],
    visibleReq: [0, 15, 30, 45, 60],
    unlockReq: [0, 5, 10, 15, 20],
    totalPower: [0.0, 0.0, 0.0, 0.0, 0.0],
    isVisible: [true, false, false, false, false],
    isUnlocked: [true, false, false, false, false],
    isActive: [false, false, false, false, false],
    xp: [0, 0, 0, 0, 0],
    xpThresh: [5, 5, 5, 5, 5],
    img: [
      "./assets/paddyPimblett.png",
      "./assets/jalinTurner.png",
      "./assets/rafaelDosAnjos.png",
      "./assets/benoitSaintDenis.png",
      "./assets/renatoMoicano.png",
    ],
    id: [
      "paddyPimblett",
      "jalinTurner",
      "rafaelDosAnjos",
      "benoitSaintDenis",
      "renatoMoicano",
    ],
    interval: [null, null, null, null, null],
    intervalIndex: null,
    divEl: [
      document.getElementById("paddyPimblettContainer") as HTMLDivElement,
      document.getElementById("jalinTurnerContainer") as HTMLDivElement,
      document.getElementById("rafaelDosAnjosContainer") as HTMLDivElement,
      document.getElementById("benoitSaintDenisContainer") as HTMLDivElement,
      document.getElementById("renatoMoicanoContainer") as HTMLDivElement,
    ],
    mastery10Unlcked: [false, false, false, false, false],
    mastery20Unlcked: [false, false, false, false, false],
    mastery30Unlcked: [false, false, false, false, false],
    mastery40Unlcked: [false, false, false, false, false],
    mastery50Unlcked: [false, false, false, false, false],
    mastery60Unlcked: [false, false, false, false, false],
    mastery70Unlcked: [false, false, false, false, false],
    mastery80Unlcked: [false, false, false, false, false],
    mastery90Unlcked: [false, false, false, false, false],
    mastery100Unlcked: [false, false, false, false, false],
    mastery10Done: 0,
    mastery20Done: 0,
    mastery30Done: 0,
    mastery40Done: 0,
    mastery50Done: 0,
    mastery60Done: 0,
    mastery70Done: 0,
    mastery80Done: 0,
    mastery90Done: 0,
    mastery100Done: 0,
    mastery10UnlockedFor5: false,
    mastery20UnlockedFor5: false,
    mastery30UnlockedFor5: false,
    mastery40UnlockedFor5: false,
    mastery50UnlockedFor5: false,
    mastery60UnlockedFor5: false,
    mastery70UnlockedFor5: false,
    mastery80UnlockedFor5: false,
    mastery90UnlockedFor5: false,
    mastery100UnlockedFor5: false,
    tags: {
      jenkki: [true, false, false, false, true],
      brassi: [false, false, true, false, false],
      striker: [true, false, false, false, false],
      grappler: [false, false, true, true, false],
      boxing: [false, false, false, false, true],
      alle30: [false, false, false, false, false],
      ladyWaist: [true, false, false, false, false],
      pelle: [false, false, false, false, false],
      niceGuy: [false, false, false, false, false],
      stan: [false, true, false, true, false],
      afrikanMafia: [false, false, false, false, false],
      lookingAss: [false, false, false, true, false],
      chad: [false, false, false, false, false],
      champion: [false, false, false, false, false],
      lasiLeuka: [false, false, false, false, false],
      legHugger: [false, false, false, false, false],
      unranked: [false, false, false, false, false],
      chicken: [false, false, false, false, false],
      hasBeen: [false, false, true, false, false],
    },
  };
  welterweightFighters = {
    nimi: [
      "Neil Magny",
      "Vicente Luque",
      "Michael Page",
      "Michael Morales",
      "Joaquin Buckley",
    ],
    power: [1.0, 1.1, 1.21, 1.331, 1.464],
    speed: [1, 0.9, 0.81, 0.729, 0.656],
    level: [0, 0, 0, 0, 0],
    hinta: [10, 100, 1_000, 10_000, 100_000],
    numero: [0, 1, 2, 3, 4],
    progress: [0, 0, 0, 0, 0],
    step: [1, 0.9, 0.81, 0.729, 0.656],
    visibleReq: [0, 15, 30, 45, 60],
    unlockReq: [0, 5, 10, 15, 20],
    totalPower: [0.0, 0.0, 0.0, 0.0, 0.0],
    isVisible: [true, false, false, false, false],
    isUnlocked: [true, false, false, false, false],
    isActive: [false, false, false, false, false],
    xp: [0, 0, 0, 0, 0],
    xpThresh: [5, 5, 5, 5, 5],
    img: [
      "./assets/neilMagny.png",
      "./assets/vicenteLuque.png",
      "./assets/michaelPage.png",
      "./assets/michaelMorales.png",
      "./assets/joaquinBuckley.png",
    ],
    id: [
      "neilMagny",
      "vicenteLuque",
      "michaelPage",
      "michaelMorales",
      "joaquinBuckley",
    ],
    interval: [null, null, null, null, null],
    intervalIndex: null,
    divEl: [
      document.getElementById("neilMagnyContainer") as HTMLDivElement,
      document.getElementById("vicenteLuqueContainer") as HTMLDivElement,
      document.getElementById("michaelPageContainer") as HTMLDivElement,
      document.getElementById("michaelMoralesContainer") as HTMLDivElement,
      document.getElementById("joaquinBuckleyContainer") as HTMLDivElement,
    ],
    mastery10Unlcked: [false, false, false, false, false],
    mastery20Unlcked: [false, false, false, false, false],
    mastery30Unlcked: [false, false, false, false, false],
    mastery40Unlcked: [false, false, false, false, false],
    mastery50Unlcked: [false, false, false, false, false],
    mastery60Unlcked: [false, false, false, false, false],
    mastery70Unlcked: [false, false, false, false, false],
    mastery80Unlcked: [false, false, false, false, false],
    mastery90Unlcked: [false, false, false, false, false],
    mastery100Unlcked: [false, false, false, false, false],
    mastery10Done: 0,
    mastery20Done: 0,
    mastery30Done: 0,
    mastery40Done: 0,
    mastery50Done: 0,
    mastery60Done: 0,
    mastery70Done: 0,
    mastery80Done: 0,
    mastery90Done: 0,
    mastery100Done: 0,
    mastery10UnlockedFor5: false,
    mastery20UnlockedFor5: false,
    mastery30UnlockedFor5: false,
    mastery40UnlockedFor5: false,
    mastery50UnlockedFor5: false,
    mastery60UnlockedFor5: false,
    mastery70UnlockedFor5: false,
    mastery80UnlockedFor5: false,
    mastery90UnlockedFor5: false,
    mastery100UnlockedFor5: false,
    tags: {
      jenkki: [true, false, false, false, true],
      brassi: [false, false, true, false, false],
      striker: [true, false, false, false, false],
      grappler: [false, false, true, true, false],
      boxing: [false, false, false, false, true],
      alle30: [false, false, false, false, false],
      ladyWaist: [true, false, false, false, false],
      pelle: [false, false, false, false, false],
      niceGuy: [false, false, false, false, false],
      stan: [false, true, false, true, false],
      afrikanMafia: [false, false, false, false, false],
      lookingAss: [false, false, false, true, false],
      chad: [false, false, false, false, false],
      champion: [false, false, false, false, false],
      lasiLeuka: [false, false, false, false, false],
      legHugger: [false, false, false, false, false],
      unranked: [false, false, false, false, false],
      chicken: [false, false, false, false, false],
      hasBeen: [false, false, true, false, false],
    }
  };
  flyweightUpgrades = {
    globalSpeedName: [
      "10% Global",
      "10% Global",
      "10% Global",
      "10% Global",
      "10% Global",
    ],
    globalSpeedDescription: [
      "10% Global",
      "10% Global",
      "10% Global",
      "10% Global",
      "10% Global",
    ],
    globalSpeedCost: [500, 500, 500, 500, 500],
    globalSpeedEffect: [1.1, 1.1, 1.1, 1.1, 1.1],
    globalSpeedIndex: [0, 1, 2, 3, 4],
    globalSpeedIsUnlocked: [false, false, false, false, false],
    globalSpeedIsPurchased: [false, false, false, false, false],
    globalPowerName: [
      "Cody Durden Power upgrade",
      "Asu Almabayev Power upgrade",
      "Bruno Silva Power upgrade",
      "Tagir Ulanbekov Power upgrade",
      "Matt Schnell Power upgrade",
    ],
    globalPowerDescription: [
      "10% Global",
      "10% Global",
      "10% Global",
      "10% Global",
      "10% Global",
    ],
    globalPowerCost: [500, 500, 500, 500, 500],
    globalPowerEffect: [1.1, 1.1, 1.1, 1.1, 1.1],
    globalPowerIndex: [0, 1, 2, 3, 4],
    globalPowerIsPurchased: [false, false, false, false, false],
    globalXpThreshName: [
      "Cody Durden XpThresh upgrade",
      "Asu Almabayev XpThresh upgrade",
      "Bruno Silva XpThresh upgrade",
      "Tagir Ulanbekov XpThresh upgrade",
      "Matt Schnell XpThresh upgrade",
    ],
    globalXpThreshDescription: [
      "1% Global",
      "1% Global",
      "1% Global",
      "1% Global",
      "1% Global",
    ],
    globalXpThreshCost: [500, 500, 500, 500, 500],
    globalXpThreshEffect: [0.99, 0.99, 0.99, 0.99, 0.99],
    globalXpThreshIndex: [0, 1, 2, 3, 4],
    globalXpThreshIsPurchased: [false, false, false, false, false],
  };
  updateUi();
  location.reload();
}